### ISSUE TITLE
Running on Local Host

### ISSUE THREAD

**Issue by Sattishh** [JulienGelmar/spotify-stats#1]
Hey, it's been 2 years since you published this repository and i really like everything about the repository. I was wondering if you could give some steps on how I could local host and try this out for myself. Thanks man

**Comment by nnsdev** [comment]
1. Install something like https://laragon.org/ to get PHP, Nginx and NodeJS. (unless you have that set up already)
2. Install https://getcomposer.org/
3. Clone this repository into the web directory of laragon (or whatever you chose)
4. `composer install` in it
5. Copy `.env.example` to `.env`
6. `php artisan k:g`
7. Go to Spotify Developer Center and set up an app, set the redirect to `https://{URL}/callback`
8. Fill in the client ID and secret in the `.env` file
9. `npm install`
10. `npm run prod` to set up the CSS and minor JS components

And then you should be good to go

**Comment by Sattishh** [comment]
Okay Thanks.
